### PR TITLE
contract is not optional

### PR DESCRIPTION
**Pull request by sjdthree**

### CODE REVIEW

**Comment by flaub** [comment]
I do think this is optional in the sense that if the contract doesn't change it shouldn't need to be republished. It also means that if two independent players want to run game, they shouldn't need to publish their own contract (and in fact this would prevent them from playing together).

This is all based on a bug that we are currently working on and hopefully will be fixed soon:
https://github.com/risc0/risc0/issues/116

**Comment by sjdthree** [comment]
Ok, it would have saved me a lot of time if I had known this when I was testing it, so how is this commit?

**Comment by flaub** [comment]
I still think that even the first time it should work out of the gate, provided that risc0/risc0#116 is fixed. Maybe adjust to refer to the bug?

**Comment by jbruestle** [comment]
Personally I think we should actually have this PR set the contract ID to <insertID> or something as well to prevent confusion.  It is just due to a bug, but until the bug is fixed, the instructions should be changed.  We can always change them back once it’s fixed (and when we do fix it we need to adjust the contract anyway).

**Comment by jbruestle** [comment]
Thanks @sjdthree for bringing this to light.  Closing in favor of https://github.com/risc0/battleship-example/pull/9 which I have added you as a co-author of.

**Pull request closed without merging**
